on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io

jobs:
  release:
    name: "Push to Registry"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image and Push to Docker Registry
        run: |
          docker buildx build --push -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{secrets.IMAGE_TAG}} \
          --build-arg username=${{secrets.APP_USER}} \
          --build-arg unique_id=${{secrets.APP_ID}} .

      - name: "Docker Scout Quickview and CVEs"
        uses: docker/scout-action@v1.16.1
        with:
          command: quickview,cves
          image: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{secrets.IMAGE_TAG}}

